// AUTO-GENERATED by scripts/curate-generation-images.ts — do not edit by hand.
// Re-run the script to refresh images or update attribution.

export interface HeroImage {
  src: string      // public path, e.g. '/images/generations/993.jpg'
  credit: string   // photographer or uploader name
  license: string  // e.g. "CC BY-SA 4.0"
  licenseUrl: string
  source: string   // Wikimedia file page URL
}

export const GENERATION_HERO_IMAGES: Record<string, HeroImage> = {
  // 911 Turbo (930) — 1600×1200
  '930': {
    src: '/images/generations/930.jpg',
    credit: 'Ermell',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Porsche_911_Turbo_(Typ_930-3.3)-_6301917.jpg',
  },
  // 911 (964) — 1600×1200
  '964': {
    src: '/images/generations/964.jpg',
    credit: 'Dawid783',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Classic_Moto_Show_2014_(116).JPG',
  },
  // Boxster (981) — 1600×1087
  '981-boxster': {
    src: '/images/generations/981.jpg',
    credit: 'Cpl.Winky',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Porsche_Cayman_S_(Type_981).jpg',
  },
  // Cayman (981) — shared hero until dedicated shot is sourced
  '981-cayman': {
    src: '/images/generations/981.jpg',
    credit: 'Cpl.Winky',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Porsche_Cayman_S_(Type_981).jpg',
  },
  // Boxster (986) — 1600×664
  '986': {
    src: '/images/generations/986.jpg',
    credit: 'Rudolf Stricker',
    license: 'CC BY-SA 3.0',
    licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Porsche_986_Boxster_side_20070522.jpg',
  },
  // 911 (992.1) — 1600×843
  '992.1': {
    src: '/images/generations/992.jpg',
    credit: 'Alexander-93',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Porsche_992_Carrera_GTS_Spirit_70_IAA_2025_DSC_1981.jpg',
  },
  // 911 (993) — 1600×672
  '993': {
    src: '/images/generations/993.jpg',
    credit: 'OSX',
    license: 'Public domain',
    licenseUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:1997_Porsche_911_Carrera_(993)_convertible_(2011-11-18)_01.jpg',
  },
  // 911 (996) — 1600×1067
  '996': {
    src: '/images/generations/996.jpg',
    credit: 'Matti Blume',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Porsche_911_GT3_Touring%2C_IAA_2017%2C_Frankfurt_(1Y7A2766).jpg',
  },
  // Boxster (987.1) — 1600×1067
  '987.1-boxster': {
    src: '/images/generations/987.1.jpg',
    credit: 'Jiří Sedláček',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Porsche_987_at_Legendy_2018_in_Prague.jpg',
  },
  // Cayman (987.1) — shared hero until dedicated shot is sourced
  '987.1-cayman': {
    src: '/images/generations/987.1.jpg',
    credit: 'Jiří Sedláček',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Porsche_987_at_Legendy_2018_in_Prague.jpg',
  },
  // Boxster (987.2) — 1600×1125
  '987.2-boxster': {
    src: '/images/generations/987.2.jpg',
    credit: 'Bull-Doser',
    license: 'Public domain',
    licenseUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:\'10_Porsche_Boxster_(MIAS).JPG',
  },
  // Cayman (987.2) — shared hero until dedicated shot is sourced
  '987.2-cayman': {
    src: '/images/generations/987.2.jpg',
    credit: 'Bull-Doser',
    license: 'Public domain',
    licenseUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:\'10_Porsche_Boxster_(MIAS).JPG',
  },
  // 911 (997.1) — 1600×973
  '997.1': {
    src: '/images/generations/997.1.jpg',
    credit: 'MrWalkr',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:2005_Porsche_911_Carrera_by_Panache_BS_O24.jpg',
  },
  // 911 (997.2) — 1600×1207
  '997.2': {
    src: '/images/generations/997.2.jpg',
    credit: 'Spanish Coches',
    license: 'CC BY 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:2009_Porsche_911_Carrera_4S_Cabrio_(997)_(3947380399).jpg',
  },
  // 911 (991.1) — 1600×1067
  '991.1': {
    src: '/images/generations/991.1.jpg',
    credit: 'Alexandre Prévot from Nancy, France',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Porsche_911_Carrera_S_Cabriolet_(7644732598).jpg',
  },
  // 911 (991.2) — 1600×1088
  '991.2': {
    src: '/images/generations/991.2.jpg',
    credit: 'Jakub "Flyz1" Maciejewski',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Porsche_911_Carrera_4S_-_prz%C3%B3d_(MSP16).jpg',
  },
  // 911 (992.2) — 1600×932 — Auto Zürich 2024 (confirmed 992.2 facelift)
  '992.2': {
    src: '/images/generations/992.2.jpg',
    credit: 'Alexander-93',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:2025_Porsche_992_Carrera_convertible_Auto_Zuerich_2024_DSC_6527.jpg',
  },
  // 718 Cayman (982) — 1600×1066 — confirmed Cayman S coupe, not Boxster/Spyder
  '982-cayman': {
    src: '/images/generations/982-cayman.jpg',
    credit: '先従隗始',
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Porsche_ABA-982J2_718_Cayman_S_(22091111324).jpg',
  },
  // 718 Boxster (982) — open top — 1600×1067
  '982-boxster': {
    src: '/images/generations/982-boxster.jpg',
    credit: '先従隗始',
    license: 'CC0',
    licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Porsche_ABA-982J2_718_Boxster_GTS_(23052112161).jpg',
  },
}
