// AUTO-GENERATED by scripts/curate-generation-images-extended.ts — do not edit by hand.
// Re-run the script to refresh variant images or update attribution.

export type ImageVariantBodyStyle = 'coupe' | 'cabriolet' | 'targa' | 'unknown'
export type ImageVariantAngle = 'front-3-4' | 'side-profile' | 'rear-3-4' | 'front' | 'rear' | 'unknown'

export interface ImageVariant {
  src: string          // public path, e.g. '/images/generations/993.jpg'
  credit: string       // photographer or uploader name
  license: string
  licenseUrl: string
  source: string       // Wikimedia file page URL
  body_style: ImageVariantBodyStyle
  color: string        // inferred color, or "unknown"
  angle: ImageVariantAngle
  is_canonical: boolean
}

export const GENERATION_IMAGE_VARIANTS: Record<string, ImageVariant[]> = {
  // 911 Turbo (930)
  '930': [
    {
      src: '/images/generations/930.jpg',
      credit: "Ermell",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_911_Turbo_(Typ_930-3.3)-_6301917.jpg",
      body_style: "coupe",
      color: "unknown",
      angle: "front-3-4",
      is_canonical: true,
    },
  ],
  // 911 (964)
  '964': [
    {
      src: '/images/generations/964.jpg',
      credit: "Dawid783",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      source: "https://commons.wikimedia.org/wiki/File:Classic_Moto_Show_2014_(116).JPG",
      body_style: "coupe",
      color: "unknown",
      angle: "front-3-4",
      is_canonical: true,
    },
    {
      src: "/images/generations/964-v2.jpg",
      credit: "Alexandre Prévot from Nancy, France",
      license: "CC BY-SA 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_964_Carrera_2_Cabriolet_(24001252515).jpg",
      body_style: "cabriolet",
      color: "unknown",
      angle: "unknown",
      is_canonical: false,
    },
    {
      src: "/images/generations/964-v3.jpg",
      credit: "Charles from Port Chester, New York",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_911_Carrera_2_Cabriolet_(964%2C_1992)_(52574989518).jpg",
      body_style: "cabriolet",
      color: "unknown",
      angle: "unknown",
      is_canonical: false,
    },
    {
      src: "/images/generations/964-v4.jpg",
      credit: "nakhon100",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_911_(964)_Carrera_2_Cabriolet_(8452024882).jpg",
      body_style: "cabriolet",
      color: "unknown",
      angle: "unknown",
      is_canonical: false,
    },
  ],
  // Boxster (981)
  '981-boxster': [
    {
      src: '/images/generations/981.jpg',
      credit: "Sarah Larson",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
      source: "https://commons.wikimedia.org/wiki/File:2013_Porsche_Panamera_Turbo_S,_Cayman,_Cayman_S,_Boxster_(8402948837).jpg",
      body_style: "cabriolet",
      color: "unknown",
      angle: "front-3-4",
      is_canonical: true,
    },
  ],
  // Cayman (981) — shared image until dedicated shot is sourced
  '981-cayman': [
    {
      src: '/images/generations/981.jpg',
      credit: "Sarah Larson",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
      source: "https://commons.wikimedia.org/wiki/File:2013_Porsche_Panamera_Turbo_S,_Cayman,_Cayman_S,_Boxster_(8402948837).jpg",
      body_style: "cabriolet",
      color: "unknown",
      angle: "front-3-4",
      is_canonical: true,
    },
  ],
  // Boxster (986)
  '986': [
    {
      src: '/images/generations/986.jpg',
      credit: "Rudolf Stricker",
      license: "CC BY-SA 3.0",
      licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_986_Boxster_side_20070522.jpg",
      body_style: "cabriolet",
      color: "silver",
      angle: "side-profile",
      is_canonical: true,
    },
  ],
  // 911 (992.1)
  '992.1': [
    {
      src: '/images/generations/992.jpg',
      credit: "Alexander-93",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_992_Carrera_GTS_Spirit_70_IAA_2025_DSC_1981.jpg",
      body_style: "coupe",
      color: "unknown",
      angle: "front-3-4",
      is_canonical: true,
    },
  ],
  // 911 (993)
  '993': [
    {
      src: '/images/generations/993.jpg',
      credit: "OSX",
      license: "Public domain",
      licenseUrl: "",
      source: "https://commons.wikimedia.org/wiki/File:1997_Porsche_911_Carrera_(993)_convertible_(2011-11-18)_01.jpg",
      body_style: "cabriolet",
      color: "silver",
      angle: "front-3-4",
      is_canonical: true,
    },
  ],
  // 911 (996)
  '996': [
    {
      src: '/images/generations/996.jpg',
      credit: "Matti Blume",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_911_GT3_Touring,_IAA_2017,_Frankfurt_(1Y7A2766).jpg",
      body_style: "coupe",
      color: "white",
      angle: "front-3-4",
      is_canonical: true,
    },
    {
      src: "/images/generations/996-v2.jpg",
      credit: "http://gl.wikipedia.org/wiki/User_talk:Norrin_strange",
      license: "Public domain",
      licenseUrl: "",
      source: "https://commons.wikimedia.org/wiki/File:Yellow_Porsche_911_Carrera_Cabriolet_Type_996.jpg",
      body_style: "cabriolet",
      color: "yellow",
      angle: "unknown",
      is_canonical: false,
    },
    {
      src: "/images/generations/996-v3.jpg",
      credit: "Cjp24",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_996_Carrera_4S_convertible_(2).jpg",
      body_style: "cabriolet",
      color: "unknown",
      angle: "unknown",
      is_canonical: false,
    },
    {
      src: "/images/generations/996-v4.jpg",
      credit: "Cjp24",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_996_Carrera_4S_convertible_(1).jpg",
      body_style: "cabriolet",
      color: "unknown",
      angle: "unknown",
      is_canonical: false,
    },
  ],
  // Boxster (987.1)
  '987.1-boxster': [
    {
      src: '/images/generations/987.1.jpg',
      credit: "Jiří Sedláček",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_987_at_Legendy_2018_in_Prague.jpg",
      body_style: "cabriolet",
      color: "unknown",
      angle: "front-3-4",
      is_canonical: true,
    },
  ],
  // Cayman (987.1) — shared image until dedicated shot is sourced
  '987.1-cayman': [
    {
      src: '/images/generations/987.1.jpg',
      credit: "Jiří Sedláček",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_987_at_Legendy_2018_in_Prague.jpg",
      body_style: "coupe",
      color: "unknown",
      angle: "front-3-4",
      is_canonical: true,
    },
  ],
  // Boxster (987.2)
  '987.2-boxster': [
    {
      src: '/images/generations/987.2.jpg',
      credit: "Bull-Doser",
      license: "Public domain",
      licenseUrl: "",
      source: "https://commons.wikimedia.org/wiki/File:'10_Porsche_Boxster_(MIAS).JPG",
      body_style: "cabriolet",
      color: "unknown",
      angle: "front-3-4",
      is_canonical: true,
    },
  ],
  // Cayman (987.2) — shared image until dedicated shot is sourced
  '987.2-cayman': [
    {
      src: '/images/generations/987.2.jpg',
      credit: "Bull-Doser",
      license: "Public domain",
      licenseUrl: "",
      source: "https://commons.wikimedia.org/wiki/File:'10_Porsche_Boxster_(MIAS).JPG",
      body_style: "coupe",
      color: "unknown",
      angle: "front-3-4",
      is_canonical: true,
    },
  ],
  // 911 (997.1)
  '997.1': [
    {
      src: '/images/generations/997.1.jpg',
      credit: "MrWalkr",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      source: "https://commons.wikimedia.org/wiki/File:2005_Porsche_911_Carrera_by_Panache_BS_O24.jpg",
      body_style: "coupe",
      color: "silver",
      angle: "front-3-4",
      is_canonical: true,
    },
  ],
  // 911 (997.2)
  '997.2': [
    {
      src: '/images/generations/997.2.jpg',
      credit: "Spanish Coches",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
      source: "https://commons.wikimedia.org/wiki/File:2009_Porsche_911_Carrera_4S_Cabrio_(997)_(3947380399).jpg",
      body_style: "cabriolet",
      color: "unknown",
      angle: "side-profile",
      is_canonical: true,
    },
  ],
  // 911 (991.1)
  '991.1': [
    {
      src: '/images/generations/991.1.jpg',
      credit: "Alexandre Prévot",
      license: "CC BY-SA 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_911_Carrera_S_Cabriolet_(7644732598).jpg",
      body_style: "cabriolet",
      color: "silver",
      angle: "side-profile",
      is_canonical: true,
    },
  ],
  // 911 (991.2)
  '991.2': [
    {
      src: '/images/generations/991.2.jpg',
      credit: "Jakub \"Flyz1\" Maciejewski",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_911_Carrera_4S_-_przód_(MSP16).jpg",
      body_style: "coupe",
      color: "unknown",
      angle: "front",
      is_canonical: true,
    },
  ],
  // 911 (992.2)
  '992.2': [
    {
      src: '/images/generations/992.2.jpg',
      credit: "Matti Blume",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_992_Cabrio,_GIMS_2019,_Le_Grand-Saconnex_(GIMS9993).jpg",
      body_style: "cabriolet",
      color: "unknown",
      angle: "front-3-4",
      is_canonical: true,
    },
  ],
  // 718 Cayman (982)
  '982-cayman': [
    {
      src: '/images/generations/982-cayman.jpg',
      credit: "Alexander-93",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_718_Boxster_Spyder_RS_IAA_2023_1X7A0535.jpg",
      body_style: "coupe",
      color: "unknown",
      angle: "front-3-4",
      is_canonical: true,
    },
  ],
  // 718 Boxster (982)
  '982-boxster': [
    {
      src: '/images/generations/982-boxster.jpg',
      credit: "先従隗始",
      license: "CC0",
      licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      source: "https://commons.wikimedia.org/wiki/File:Porsche_ABA-982J2_718_Boxster_GTS_(23052112161).jpg",
      body_style: "cabriolet",
      color: "unknown",
      angle: "front-3-4",
      is_canonical: true,
    },
  ],
}

/**
 * Returns the best image for a given generation + optional body style preference.
 * Falls back to the canonical image if no variant matches.
 */
export function pickGenerationImage(
  generationId: string,
  preferBodyStyle?: ImageVariantBodyStyle,
): ImageVariant | null {
  const variants = GENERATION_IMAGE_VARIANTS[generationId]
  if (!variants || variants.length === 0) return null
  if (preferBodyStyle && preferBodyStyle !== "unknown") {
    const match = variants.find(
      (v) => v.body_style === preferBodyStyle && !v.is_canonical,
    )
    if (match) return match
  }
  // Fall back to canonical
  return variants.find((v) => v.is_canonical) ?? variants[0]
}
