-- =============================================================================
-- Comp Engine V2 — Phase 1, Step 5
-- Create comp_engine_runs table.
-- Every prediction logged, no exceptions, no sampling.
--
-- subject_listing_id: real listing ID (production + backtest runs).
-- subject_data: full subject JSONB for hypothetical subjects (future use).
--   Both nullable; at least one should be populated per run.
--
-- model_version: bumped on every weight or logic change (e.g., "v1.0", "v1.1").
-- generation_used: which generation's weight config was actually applied.
-- weights_json: snapshot of exact weights at prediction time.
-- comps_used_json: array of {listing_id, similarity, recency_weight, final_weight}.
--
-- RLS: service role write; no public read (internal analytics only).
-- Apply: npx supabase db push
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS comp_engine_runs (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

  subject_listing_id  UUID        REFERENCES listings(id) ON DELETE SET NULL,
  subject_data        JSONB,

  model_version       TEXT        NOT NULL,
  generation_used     TEXT        NOT NULL,
  weights_json        JSONB       NOT NULL,
  comps_used_json     JSONB       NOT NULL DEFAULT '[]',

  predicted_median    BIGINT,
  predicted_p25       BIGINT,
  predicted_p75       BIGINT,
  confidence_score    NUMERIC(5,2)
    CONSTRAINT comp_engine_runs_confidence_range
    CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)),
  methodology_text    TEXT,

  -- Backtest fields
  actual_price        BIGINT,
  was_backtest        BOOLEAN NOT NULL DEFAULT false,

  -- Verdict for insufficient/uncomparable cases
  verdict             TEXT
    CONSTRAINT comp_engine_runs_verdict_check
    CHECK (verdict IS NULL OR verdict IN ('priced_fairly','priced_above','priced_below',
                                          'insufficient_comps','uncomparable','low_confidence'))
);

COMMENT ON TABLE comp_engine_runs IS
  'Every comp engine prediction logged here, no sampling. model_version string is bumped on every weight or logic change. Primary substrate for backtesting and retrospective analysis.';

COMMENT ON COLUMN comp_engine_runs.subject_listing_id IS
  'FK to listings for real listing predictions and backtest runs. NULL for hypothetical subjects.';

COMMENT ON COLUMN comp_engine_runs.subject_data IS
  'Full subject JSONB snapshot for hypothetical subjects or replay without needing the original listing.';

COMMENT ON COLUMN comp_engine_runs.generation_used IS
  'Which generation config was actually applied. May differ from subject generation_id when falling back to default.';

COMMENT ON COLUMN comp_engine_runs.weights_json IS
  'Exact weights used at prediction time — snapshot for reproducibility.';

COMMENT ON COLUMN comp_engine_runs.comps_used_json IS
  'Array of {listing_id, similarity_score, recency_weight, final_weight, price_cents}.';

COMMENT ON COLUMN comp_engine_runs.confidence_score IS
  '0–100 computed score. Not surfaced in UI in V1. Stored for retrospective analysis.';

COMMENT ON COLUMN comp_engine_runs.methodology_text IS
  'Human-readable methodology line. Not surfaced in UI in V1.';

COMMENT ON COLUMN comp_engine_runs.actual_price IS
  'Actual sale price in cents. Populated for backtest runs from final_price.';

COMMENT ON COLUMN comp_engine_runs.was_backtest IS
  'True when this run was generated by the backtest harness, not a live user request.';

COMMENT ON COLUMN comp_engine_runs.verdict IS
  'Final price verdict. NULL means run ended in insufficient_comps or uncomparable.';

CREATE INDEX IF NOT EXISTS comp_engine_runs_subject_listing_id_idx
  ON comp_engine_runs (subject_listing_id)
  WHERE subject_listing_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS comp_engine_runs_model_version_idx
  ON comp_engine_runs (model_version, created_at DESC);

CREATE INDEX IF NOT EXISTS comp_engine_runs_backtest_idx
  ON comp_engine_runs (was_backtest, model_version)
  WHERE was_backtest = true;

-- ---------------------------------------------------------------------------
-- RLS: service role writes. No public read — this is internal analytics.
-- Authenticated users can read their own runs via subject_listing_id.
-- ---------------------------------------------------------------------------

ALTER TABLE comp_engine_runs ENABLE ROW LEVEL SECURITY;

-- Admins and service role can read all runs
DROP POLICY IF EXISTS comp_engine_runs_service_read ON comp_engine_runs;
CREATE POLICY comp_engine_runs_service_read
  ON comp_engine_runs FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM users
      WHERE users.id = auth.uid()
        AND users.role IN ('admin', 'beta')
    )
  );

GRANT SELECT, INSERT, UPDATE ON comp_engine_runs TO service_role;
GRANT SELECT ON comp_engine_runs TO authenticated;

COMMIT;


-- =============================================================================
-- ROLLBACK — do not apply automatically
-- =============================================================================
-- BEGIN;
-- REVOKE SELECT, INSERT, UPDATE ON comp_engine_runs FROM service_role;
-- REVOKE SELECT ON comp_engine_runs FROM authenticated;
-- DROP TABLE IF EXISTS comp_engine_runs;
-- COMMIT;
